// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Run: npm run logos:sync
// Curated bundled logos only. Missing keys fall through to brand-color initials avatars (100% offline).
export const INSTITUTION_LOGO_ASSETS: Record<string, number> = {
  aub: require("../../../assets/institutions/aub.png"),
  bdo: require("../../../assets/institutions/bdo.png"),
  bpi: require("../../../assets/institutions/bpi.png"),
  chinabank: require("../../../assets/institutions/chinabank.png"),
  cimb: require("../../../assets/institutions/cimb.png"),
  "col-financial": require("../../../assets/institutions/col-financial.png"),
  "ctbc-bank": require("../../../assets/institutions/ctbc-bank.png"),
  "eastwest-bank": require("../../../assets/institutions/eastwest-bank.png"),
  firstmetrosec: require("../../../assets/institutions/firstmetrosec.png"),
  gcash: require("../../../assets/institutions/gcash.png"),
  gotyme: require("../../../assets/institutions/gotyme.png"),
  grabpay: require("../../../assets/institutions/grabpay.png"),
  gsis: require("../../../assets/institutions/gsis.png"),
  landbank: require("../../../assets/institutions/landbank.png"),
  maribank: require("../../../assets/institutions/maribank.png"),
  maya: require("../../../assets/institutions/maya.png"),
  metrobank: require("../../../assets/institutions/metrobank.png"),
  ofbank: require("../../../assets/institutions/ofbank.png"),
  pagibig: require("../../../assets/institutions/pagibig.png"),
  philhealth: require("../../../assets/institutions/philhealth.png"),
  pnb: require("../../../assets/institutions/pnb.png"),
  psbank: require("../../../assets/institutions/psbank.png"),
  rcbc: require("../../../assets/institutions/rcbc.png"),
  "robinsons-bank": require("../../../assets/institutions/robinsons-bank.png"),
  "security-bank": require("../../../assets/institutions/security-bank.png"),
  shopeepay: require("../../../assets/institutions/shopeepay.png"),
  sss: require("../../../assets/institutions/sss.png"),
  tonik: require("../../../assets/institutions/tonik.png"),
  unionbank: require("../../../assets/institutions/unionbank.png"),
};
